### ISSUE TITLE
With plugin enabled receive error when opening settings

### ISSUE THREAD

**Issue by gandalf428** [eideasy/nextcloud-electronic-signatures-plugin#32]
After installing this plugin I receive an error (see attached pic) when attempting to open the user settings (as NC admin). If I disable the plugin everything works as it should. I'm new to NC, so I'm not very familiar with the internal workings.

![NC Error with Elec Sig Enabled](https://user-images.githubusercontent.com/20098567/122648911-da696200-d0f0-11eb-8687-218205d512c7.PNG)

From error log:

{"reqId":"6aJAfsjJ2POAFrTTgz8r","level":3,"time":"2021-06-19T15:07:11+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxADMINUSERxx","app":"index","method":"GET","url":"/index.php/settings/user","message":{"Exception":"Exception","Message":"syntax error, unexpected 'IConfig' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\PersonalSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"personal-info","_route":"settings.PersonalSettings.index"}]},{"file":"/var/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/user"]},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":159,"Previous":{"Exception":"ParseError","Message":"syntax error, unexpected 'IConfig' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/composer/composer/ClassLoader.php","line":346,"function":"Composer\\Autoload\\includeFile","args":["/var/www/nextcloud/apps/electronicsignatures/lib//Config.php"]},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->","args":["OCA\\ElectronicSignatures\\Config"]},{"function":"spl_autoload_call","args":["OCA\\ElectronicSignatures\\Config"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":107,"function":"__construct","class":"ReflectionClass","type":"->","args":["OCA\\ElectronicSignatures\\Config"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":126,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\ElectronicSignatures\\Config"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":459,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\ElectronicSignatures\\Config"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":431,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\ElectronicSignatures\\Config"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\ElectronicSignatures\\Config",true]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":101,"function":"array_map","args":[{"__class__":"Closure"},[{"name":"config","__class__":"ReflectionParameter"},"*** sensitive parameter replaced ***"]]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":109,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\ElectronicSignatures\\Settings\\Admin","__class__":"ReflectionClass"}]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":126,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\ElectronicSignatures\\Settings\\Admin"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":459,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\ElectronicSignatures\\Settings\\Admin"]},{"file":"/var/www/nextcloud/lib/private/ServerContainer.php","line":146,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\ElectronicSignatures\\Settings\\Admin"]},{"file":"/var/www/nextcloud/lib/private/Settings/Manager.php","line":171,"function":"query","class":"OC\\ServerContainer","type":"->","args":["OCA\\ElectronicSignatures\\Settings\\Admin"]},{"file":"/var/www/nextcloud/lib/private/Settings/Manager.php","line":233,"function":"getSettings","class":"OC\\Settings\\Manager","type":"->","args":["admin","overview"]},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":91,"function":"getAdminSettings","class":"OC\\Settings\\Manager","type":"->","args":["overview",false]},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":124,"function":"formatSections","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":[[[{"__class__":"OCA\\Settings\\Sections\\Admin\\Overview"}],[{"__class__":"OCA\\Support\\Settings\\Section"},{"__class__":"OCA\\Settings\\Sections\\Admin\\Server"}],[{"__class__":"OCA\\Settings\\Sections\\Admin\\Sharing"}],[{"__class__":"OCA\\Settings\\Sections\\Admin\\Security"},{"__class__":"OCA\\Files_External\\Settings\\Section"}],[{"__class__":"OCA\\Theming\\Settings\\Section"}],"And 6 more entries, set log level to debug to see all entries"],"personal-info","admin","personal",false]},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":76,"function":"formatAdminSections","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info",false]},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":148,"function":"getNavigationParameters","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info"]},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/PersonalSettingsController.php","line":68,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"index","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal-info"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\PersonalSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"personal-info","_route":"settings.PersonalSettings.index"}]},{"file":"/var/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/user"]},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/electronicsignatures/lib/Config.php","Line":11},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36","version":"21.0.2.1"}

**Comment by tpalts** [comment]
Hey! Are you using a php version below 7.4 ?

**Comment by gandalf428** [comment]
Apparently I have PHP 7.3.27-1~deb10u1. This instance is on Linode using their Marketplace Nextcloud deployment. I’ll see if I can get PHP upgraded to 7.4. Thanks for the info.

**Comment by tpalts** [comment]
Let me know how it goes!

**Comment by ghost** [comment]
Same problem for me. Solved after deactivated that plugin

**Comment by tpalts** [comment]
@DanieleMar , are you seeing the same error in your log, as @gandalf428 :

`syntax error, unexpected 'IConfig'`

If yes, try upgrading to php 7.4 or later.

**Comment by tpalts** [comment]
@gandalf428 @DanieleMar the latest release of the app (1.2.0) supports php 7.3, so your issues should be resolved.
