### ISSUE TITLE
Request for feature: Support for multiple signature signing and order

### ISSUE THREAD

**Issue by magnetic5355** [eideasy/nextcloud-electronic-signatures-plugin#46]

**Comment by tpalts** [comment]
@caesarcxiv Can you describe in more detail, what do you mean by "order" in this case? What should the user experience look like and what is the real world use case?

**Comment by smartman** [comment]
@caesarcxiv I believe you need to set multiple e-mails of people who need to sign the doc and you want to say who is 1st, who 2nd and so on. Can you write to support@eideasy.com and tell a bit more about your business case, how many signatures are you planning to have so we can plan the new request release?

**Comment by matsjoonas** [comment]
@caesarcxiv I'm happy to let you know that our plugin now supports adding multiple signers.
