### ISSUE TITLE
Fails upgrade

### ISSUE THREAD

**Issue by MRFU510N88** [eideasy/nextcloud-electronic-signatures-plugin#49]
Fails upgrade today to latest with error:

'The column 'is_downloaded' on table 'oc_esignature_sessions' already exists'

This also locked my NC sever into maint mode and could not access hub without first uninstalling the app via console. 

I also cannot do a new install of the app via web, I get the same error message

**Comment by tpalts** [comment]
Try our latest release (1.4.0). Did it fix your problems?

**Comment by MRFU510N88** [comment]
That was a fast fix hat off to you,

Yes its installed now without any visible issues thankyou.
