### ISSUE TITLE
Sending mail via the 'Signing' popup fails

### ISSUE THREAD

**Issue by hydazz** [eideasy/nextcloud-electronic-signatures-plugin#55]
When trying to send an email via the send signing link via the email popup it errors out with `Expected response code 354 but got code 554, with message "554 5.5.1 Error: no valid recipients"`. Sending mail via any other means in nextcloud works, sending the test mail works as well. It seems the built-in implementation of the [mailer here](https://github.com/eideasy/nextcloud-electronic-signatures-plugin/blob/master/lib/Commands/SendSigningLinkToEmail.php) isn't playing well with my nextcloud environment, which is an alpine docker container running nextcloud 21.0.3 on PHP 8 and Nginx 1.20.1. Using the local option in settings, the pades-external-digital-signatures container is setup and working. I have forever had issues with mailing in my environment but if sending mail via nextcloud works I don't see why this can't work as well. Any ideas here? I'm keen to try this app out!

```json
}{
   "reqId":"pjFVTXYSnQq0ukOmeyz0",
   "level":3,
   "time":"2021-07-07T14:03:47+00:00",
   "remoteAddr":"[redacted]",
   "user":"alex",
   "app":"electronicsignatures",
   "method":"POST",
   "url":"/apps/electronicsignatures/send_sign_link_by_email",
   "message":"basinga  44",
   "userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
   "version":"21.0.3.1"
}{
   "reqId":"pjFVTXYSnQq0ukOmeyz0",
   "level":3,
   "time":"2021-07-07T14:03:47+00:00",
   "remoteAddr":"[redacted]",
   "user":"alex",
   "app":"electronicsignatures",
   "method":"POST",
   "url":"/apps/electronicsignatures/send_sign_link_by_email",
   "message":"conttype pdf",
   "userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
   "version":"21.0.3.1"
}{
   "reqId":"pjFVTXYSnQq0ukOmeyz0",
   "level":3,
   "time":"2021-07-07T14:03:48+00:00",
   "remoteAddr":"[redacted]",
   "user":"alex",
   "app":"electronicsignatures",
   "method":"POST",
   "url":"/apps/electronicsignatures/send_sign_link_by_email",
   "message":"Expected response code 354 but got code \"554\", with message \"554 5.5.1 Error: no valid recipients\r\n\". Did you set up your email server correctly?\n#0 /config/www/storage.hydesign.com.au/public_html/apps/electronicsignatures/lib/Controller/SignApiController.php(94): OCA\\ElectronicSignatures\\Commands\\SendSigningLinkToEmail->sendIfNecessary()\n#1 /config/www/storage.hydesign.com.au/public_html/lib/private/AppFramework/Http/Dispatcher.php(218): OCA\\ElectronicSignatures\\Controller\\SignApiController->sendSignLinkByEmail()\n#2 /config/www/storage.hydesign.com.au/public_html/lib/private/AppFramework/Http/Dispatcher.php(127): OC\\AppFramework\\Http\\Dispatcher->executeController()\n#3 /config/www/storage.hydesign.com.au/public_html/lib/private/AppFramework/App.php(157): OC\\AppFramework\\Http\\Dispatcher->dispatch()\n#4 /config/www/storage.hydesign.com.au/public_html/lib/private/Route/Router.php(302): OC\\AppFramework\\App::main()\n#5 /config/www/storage.hydesign.com.au/public_html/lib/base.php(993): OC\\Route\\Router->match()\n#6 /config/www/storage.hydesign.com.au/public_html/index.php(37): OC::handleRequest()\n#7 {main}",
   "userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
   "version":"21.0.3.1"
}
```

**Comment by tpalts** [comment]
Hi @hydazz . Our mailer implementation is based on other Nextcloud-endorsed apps and it seems to work reliably in all of the setups we have tested it in. The error description you provided ("no valid recipients") returns quite a few discussions from Google.

[This one](https://help.nextcloud.com/t/server-error-after-sending-reistration-link/80925/3) seems like the most promising:

> [...] After switching to “sendmail”, [problem is fixed].
> [...] they had given an email address that did not come from “my” mail server. Therefore I could not reproduce the error with my own email address.

So perhaps the email server that you use does not allow sending e-mail to recipients in some specific domain?

**Comment by hydazz** [comment]
From the logs of the mail server:
```
postfix/submission/smtpd[1846]: NOQUEUE: reject: RCPT from [redacted]: 553 5.7.1 <alexanderhyde@icloud.com>: Sender address rejected: not owned by user no-reply@hydesign.com.au; from=<alexanderhyde@icloud.com> to=<alexanderhyde@icloud.com> proto=ESMTP helo=<storage.hydesign.com.au>
```
It looks as nextcloud is trying to use the to/destination/recipient as the from address and as the mail server is setup properly it sees this as trying to forge the from address and is blocking it. sendmail is not an option here as I do need to use a real mailserver that has proper support for dkim and such so mail does not get marked as spam

**Comment by hydazz** [comment]
Here is the error output with SMTP debug enabled. nextcloud is configured to send mails from `no-reply@hydesign.com.au`. again the `>> MAIL FROM:<alexanderhyde@icloud.com>` is standing out here, as I would think it should be more like `>> MAIL FROM:<no-reply@hydesign.com.au>`

```php
Failed to send email: Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients
"
Log data:
++ Starting Swift_SmtpTransport
<< 220 mail.hyde.services ESMTP

>> EHLO storage.hydesign.com.au

<< 250-mail.hyde.services
250-PIPELINING
250-SIZE 67108864
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 CHUNKING

>> STARTTLS

<< 220 2.0.0 Ready to start TLS

>> EHLO storage.hydesign.com.au

<< 250-mail.hyde.services
250-PIPELINING
250-SIZE 67108864
250-ETRN
250-AUTH PLAIN LOGIN
250-AUTH=PLAIN LOGIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 CHUNKING

>> AUTH LOGIN

<< 334 ...

>> ...

<< 334 ...

>> ...

<< 235 2.7.0 Authentication successful

++ Swift_SmtpTransport started
>> MAIL FROM:<alexanderhyde@icloud.com>

>> RCPT TO:<alexanderhyde@icloud.com>

>> DATA

<< 250 2.1.0 Ok

<< 553 5.7.1 <alexanderhyde@icloud.com>: Sender address rejected: not owned by user no-reply@hydesign.com.au

!! Expected response code 250/251/252 but got code "553", with message "553 5.7.1 <alexanderhyde@icloud.com>: Sender address rejected: not owned by user no-reply@hydesign.com.au
" (code: 553)
<< 554 5.5.1 Error: no valid recipients

!! Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients
" (code: 554)

**Comment by hydazz** [comment]
By forcing the from address [here](https://github.com/eideasy/nextcloud-electronic-signatures-plugin/blob/master/lib/Commands/SendSigningLinkToEmail.php#L76) by changing it to `$message->setFrom(['no-reply@hydesign.com.au' => 'HYDESIGN']);` I am now able to successfully send emails via the signing popup. I don't really understand PHP but perhaps it's somehow grabbing the recipient address instead of the from address?

**Comment by tpalts** [comment]
@hydazz Please check our latest release (v1.6.1). We modified the e-mail sending so that it uses the system default address as the FROM address, instead of the current user's e-mail address. This should fix your problem.

Let us know how it goes!

**Comment by hydazz** [comment]
@tpalts 
> Let us know how it goes!

I can confirm, that in my environment it now does work.
