### ISSUE TITLE
after running make command, installation is getting stuck in between

### ISSUE THREAD

**Issue by Priyanka-cis** [eideasy/nextcloud-electronic-signatures-plugin#65]
Please let me know if we need some configuration required, installation is not getting complete. I tried many times. Please see the attached screenshot of terminal.
![Uploading Screenshot from 2021-10-13 12-15-17.png…]()

**Comment by tpalts** [comment]
Hi, @Priyanka-cis . The readme file is misleading, we will fix it soon. We recommend that you install the app by using your Nextcloud instance's "Apps" page.

If for some reason this is not possible in your case, please download our latest build and extract it into your apps directory. After this, enable the app in the "Apps" page.

Please let us know if the installation succeeds!
