### ISSUE TITLE
Questions about how it works.

### ISSUE THREAD

**Issue by pierreozoux** [eideasy/nextcloud-electronic-signatures-plugin#78]
Hi!

And thanks for this plugin!

In France, to apply to public offers, we need to sign documents, like PDF.
There are 2 norms:
 - pades
 - cades

And to sign, you need an eidas key.

Does eideasy supports all these norms?

Is it possible to host the backend ourself as well?

Thanks for all the info!

**Comment by matsjoonas** [comment]
Closing this since someone from our side already discussed this with pierreozoux
