### ISSUE TITLE
Nextcloud 25 support

### ISSUE THREAD

**Issue by sunjam** [eideasy/nextcloud-electronic-signatures-plugin#81]
Haven't tested compatibility on the new 25, which will release tomorrow the 18th.  Just an fyi.

**Comment by matsjoonas** [comment]
Thanks for letting us know!
We are currently working on making it compatible with NC25.

**Comment by p-bo** [comment]
Just in case it wasn't noticed - Nextcloud improved policy regarding changes in core to ease app developers in maintaining compatibility with newer Nextcloud versions:

https://help.nextcloud.com/t/new-process-for-documenting-core-code-changes-that-affect-app-developers/149828?u=p-bo

**Comment by webermax** [comment]
Any update on NC 25 release?

**Comment by matsjoonas** [comment]
We are now testing the new release and will hopefully publish it already in the coming days.

**Comment by matsjoonas** [comment]
@webermax @sunjam
Release 2.0.3 (with support for NC 25 ) is now up in the Nextcloud app store :)
https://apps.nextcloud.com/apps/electronicsignatures
