### ISSUE TITLE
Gather several signatures onto an existing file

### ISSUE THREAD

**Issue by herpsonc** [eideasy/nextcloud-electronic-signatures-plugin#91]
Hi,

We are studying the opportunity to use eideasy, and its integration with nextcloud is a key-point in our future decision.
Most of our contract documents require to be signed by several actors. 
Does your roadmap include this feature? And if so, what is the expected timeframe ?

**Comment by matsjoonas** [comment]
Hi,

We currently do not have this feature in our roadmap, however we might add it if there's enough need.
I'll write to you directly by email to discuss the requirements.

**Comment by matsjoonas** [comment]
Hi,

The latest app version supports signing documents by multiple parties.


Best,
