### ISSUE TITLE
Option to sign a file not being displayed

### ISSUE THREAD

**Issue by oliveiraigorm** [eideasy/nextcloud-electronic-signatures-plugin#92]
I've installed the app, set up the credentials from eideasy but the option to sing a pdf file that should be shown on the file options is not being displayed

**Comment by matsjoonas** [comment]
Hello!

What is your Nextcloud version?

**Comment by oliveiraigorm** [comment]
> Hello!
> 
> What is your Nextcloud version?

Thanks for the quick response. I'm using NC 28.0.1. 
I now see that the latest supported is 27

**Comment by matsjoonas** [comment]
Yes, currently the latest supported version is 27 but we are planning to release a new version of the app with support for NC 28+ either today or tomorrow.

**Comment by oliveiraigorm** [comment]
That's good to hear. Looking forward to it

**Comment by matsjoonas** [comment]
Just letting you know that a new version of the app with support for NC 28+is now published.
